name: Update README with New Idea

on:
  push:
    branches:
      - main
    paths:
      - 'ideas/**'
  pull_request:
    types: [closed]
    branches:
      - main
    paths:
      - 'ideas/**'

jobs:
  update-readme:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.pull_request.merged == true)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install pyyaml

      - name: Find modified or added Markdown files
        run: |
          # Find all modified or added Markdown files in the ideas/ directory
          IDEA_FILES=$(git diff-tree --no-commit-id --name-only --diff-filter=AM -r HEAD -- 'ideas/')
          if [ -z "$IDEA_FILES" ]; then
            echo "No modified or added idea files found."
            exit 0
          fi

          # Process each file
          for IDEA_FILE in $IDEA_FILES; do
            echo "Processing file: $IDEA_FILE"
            python scripts/parse_idea.py "$IDEA_FILE"
          done

      - name: Debug README content
        run: cat README.md

      - name: Commit and push changes
        run: |
          if git diff --quiet README.md; then
            echo "No changes to README.md. Skipping commit."
          else
            git config --global user.name "github-actions[bot]"
            git config --global user.email "github-actions[bot]@users.noreply.github.com"
            git add README.md
            git commit -m "Update README with new idea"
            git push