name: Update README with New Idea

on:
  push:
    branches:
      - main
    paths:
      - 'ideas/**'
  pull_request:
    types: [closed]
    branches:
      - main
    paths:
      - 'ideas/**'

jobs:
  update-readme:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.pull_request.merged == true)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install pyyaml

      - name: Extract idea data and update README
        run: |
          # Find the latest added Markdown file
          IDEA_FILE=$(git diff-tree --no-commit-id --name-only --diff-filter=A -r HEAD -- 'ideas/')
          if [ -z "$IDEA_FILE" ]; then
            echo "No new idea file added."
            exit 0
          fi

          # Parse the Markdown file and update README
          python scripts/parse_idea.py "$IDEA_FILE"

      - name: Debug README content
        run: cat README.md

      - name: Commit and push changes
        run: |
          if git diff --quiet README.md; then
            echo "No changes to README.md. Skipping commit."
          else
            git config --global user.name "github-actions[bot]"
            git config --global user.email "github-actions[bot]@users.noreply.github.com"
            git add README.md
            git commit -m "Update README with new idea"
            git push
          fi
